#language: es

Característica: SP-RECHARGE-VALIDATE-SERVICE
  Validar la condición de la línea para que pueda realizar una recarga de saldo, y retornar datos propios de la misma.


  Esquema del escenario: Validacion de status para el servicio SP-RECHARGE-VALIDATE-SERVICE
    Dado que esta  configurada la especificacion de solicitud con los headers:<headerName1>,<headerValue1>,<headerName2>,<headerValue2>,<headerName3>,<headerValue3>
    Y la entrada:<validations>,<lineaPaying>,<lineaReceiving>, la salida:<validation>,<execute>,<cellularNumber>,<billNumber>,<businessType>,<planId>,<reason>,<category>
    Cuando ejecuto la solicitud
    Entonces Se obtiene el <statusCode>


    @PSP-8194
    Ejemplos:
      | statusCode | validations     | lineaPaying | lineaReceiving | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | headerName1 | headerValue1   | headerName2 | headerValue2   | headerName3  | headerValue3     |
      | 200        | BUSINESS REASON | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 404        | BUSINESS        | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | pruebaError  | pruebaError      |


  Esquema del escenario: Validacion mensajes de error para el servicio SP-RECHARGE-VALIDATE-SERVICE
    Dado que esta  configurada la especificacion de solicitud con los headers:<headerName1>,<headerValue1>,<headerName2>,<headerValue2>,<headerName3>,<headerValue3>
    Y entrada: <validations>,<lineaPaying>,<lineaReceiving>, la salida: <validation>,<execute>,<cellularNumber>,<planId>,<reason>,<category>
    Cuando ejecuto la solicitud
    Entonces Se obtiene el <statusCode>
    Y Se verifica el mensaje de salida <mensaje>


    @PSP-8195
    Ejemplos:
      | statusCode | validations             | lineaPaying | lineaReceiving | validation | execute | cellularNumber | planId | reason | category | headerName1 | headerValue1   | headerName2 | headerValue2   | headerName3  | headerValue3     | mensaje                                                                     |
      #| 200        | BUSINESS    | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | pruebaError | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json | Error el campo Session-Id es nulo o vacio                                   |
      #| 200        | BUSINESS    | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | pruebaError | Channel Prueba | Content-Type | application/json | Error el campo Channel-Id es nulo o vacio                                   |
      #| 200        | BUSINESS    | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | pruebaError | Session Prueba | pruebaError | Channel Prueba | Content-Type | application/json | Error el campo Session-Id, Channel-Id es nulo o vacio                       |
      #| 404        | BUSINESS    | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | pruebaError  | pruebaError      | Not Found                                                                   |
      | 200        | BUSINESS                | 213213123   | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | 123123         | Channel-Id  | PDC            | Content-Type | application/json | Error no se encontraron registros en CELLULARS_PLANS con el valor 213213123 |
      #| 200        | BUSINESS    | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | pruebaError | Channel Prueba | Content-Type | application/json | Error el campo Channel-Id es nulo o vacio                                   |
      #| 200        | BUSINESS    | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | pruebaError | Session Prueba | pruebaError | Channel Prueba | Content-Type | application/json | Error el campo Session-Id, Channel-Id es nulo o vacio                       |

      | 200        | BUSINESS REASON CHANNEL | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON BUSINESS CHANNEL | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL BUSINESS REASON | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS CHANNEL REASON | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON CHANNEL BUSINESS | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL REASON BUSINESS | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS REASON         | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS CHANNEL        | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON BUSINESS         | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON CHANNEL          | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL BUSINESS        | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL REASON          | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL                 | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS                | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON                  | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON                  | 5456456465  | 3515572975     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS REASON CHANNEL | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON BUSINESS CHANNEL | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL BUSINESS REASON | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS CHANNEL REASON | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON CHANNEL BUSINESS | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL REASON BUSINESS | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS REASON         | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS CHANNEL        | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON BUSINESS         | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON CHANNEL          | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL BUSINESS        | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL REASON          | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL                 | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS                | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON                  | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | REASON                  | 3515572975  | 5456456465     | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | PDC            | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS REASON CHANNEL |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | REASON BUSINESS CHANNEL |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL BUSINESS REASON |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS CHANNEL REASON |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | REASON CHANNEL BUSINESS |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL REASON BUSINESS |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS REASON         |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS CHANNEL        |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | REASON BUSINESS         |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | REASON CHANNEL          |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL BUSINESS        |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL REASON          |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | CHANNEL                 |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | BUSINESS                |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | REASON                  |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |
      | 200        | REASON                  |             |                | validation | execute | cellularNumber | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |                                                                             |


  Esquema del escenario: Validacion estructura de respuesta del servicio SP-RECHARGE-VALIDATE-SERVICE
    Dado que esta  configurada la especificacion de solicitud con los headers:<headerName1>,<headerValue1>,<headerName2>,<headerValue2>,<headerName3>,<headerValue3>
    Y la entrada:<validations>,<lineaPaying>,<lineaReceiving>, la salida:<validation>,<execute>,<cellularNumber>,<billNumber>,<businessType>,<planId>,<reason>,<category>
    Cuando ejecuto la solicitud
    Entonces Se obtiene el <statusCode>
    Y Se valida la estructura de la respuesta


    @PSP-8196
    Ejemplos:
      | statusCode | validations     | lineaPaying | lineaReceiving | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | headerName1 | headerValue1   | headerName2 | headerValue2   | headerName3  | headerValue3     |
      | 200        | BUSINESS REASON | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |


  Esquema del escenario: Validacion exitosa del contenido del response, del servicio SP-RECHARGE-VALIDATE-SERVICE
    Dado que esta  configurada la especificacion de solicitud con los headers:<headerName1>,<headerValue1>,<headerName2>,<headerValue2>,<headerName3>,<headerValue3>
    Y la entrada:<validations>,<lineaPaying>,<lineaReceiving>, la salida:<validation>,<execute>,<cellularNumber>,<billNumber>,<businessType>,<planId>,<reason>,<category>
    Cuando ejecuto la solicitud
    Entonces Se obtiene el <statusCode>
    Y Se validan los datos de la respuesta



    @PSP-8197
    Ejemplos:
      | statusCode | validations             | lineaPaying | lineaReceiving | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | headerName1 | headerValue1   | headerName2 | headerValue2   | headerName3  | headerValue3     |
      | 200        | BUSINESS REASON CHANNEL | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | REASON BUSINESS CHANNEL | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | CHANNEL BUSINESS REASON | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | BUSINESS CHANNEL REASON | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | REASON CHANNEL BUSINESS | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | CHANNEL REASON BUSINESS | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | BUSINESS REASON         | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | BUSINESS CHANNEL        | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | REASON BUSINESS         | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | REASON CHANNEL          | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | CHANNEL BUSINESS        | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | CHANNEL REASON          | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | CHANNEL                 | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | BUSINESS                | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | REASON                  | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        | REASON                  | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |
      | 200        |                         | 3515572975  | 3515572975     | validation | execute | cellularNumber | billNumber | businessType | planId | reason | category | Session-Id  | Session Prueba | Channel-Id  | Channel Prueba | Content-Type | application/json |

